; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
platform = espressif32 @ 6.13.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs
lib_deps = 
    marcoschwartz/LiquidCrystal_I2C @ 1.1.4
    adafruit/RTClib @ 2.1.4
    ESP32Async/ESPAsyncWebServer @ 3.10.3
    ESP32Async/AsyncTCP @ 3.4.10
    bblanchon/ArduinoJson @ 7.4.3
    adafruit/Adafruit Thermal Printer Library @ ^1.4.1
    ayushsharma82/ElegantOTA @ ^3.1.6
    jandrassy/TelnetStream @ ^1.3.0

[env:esp32s3_standard]
extends = common
build_flags = 
    -DBOARD_HAS_PSRAM
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
    -DUSB_HOST_TASK_STACK_SIZE=4096
    -DMODE_CONTINUOUS
    -DSUPPORT_USB
    -DUSE_A12E_PROTOCOL

[env:esp32s3_logam_jaya]
extends = common
build_flags = 
    -DBOARD_HAS_PSRAM
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
    -DMODE_COMMAND
    -DTICKET_LOGAM_JAYA
    -DUSE_A12E_PROTOCOL